// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/tumpal2796/sophee/bill/model"

// BillInf is an autogenerated mock type for the BillInf type
type BillInf struct {
	mock.Mock
}

// GetMyBill provides a mock function with given fields:
func (_m *BillInf) GetMyBill() (model.Bill, error) {
	ret := _m.Called()

	var r0 model.Bill
	if rf, ok := ret.Get(0).(func() model.Bill); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.Bill)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
