// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "github.com/tumpal2796/shopee/transaction/model"

// TransactionInf is an autogenerated mock type for the TransactionInf type
type TransactionInf struct {
	mock.Mock
}

// GetAllTransaction provides a mock function with given fields: ctx
func (_m *TransactionInf) GetAllTransaction(ctx context.Context) ([]model.Transaction, error) {
	ret := _m.Called(ctx)

	var r0 []model.Transaction
	if rf, ok := ret.Get(0).(func(context.Context) []model.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, transaction
func (_m *TransactionInf) Insert(ctx context.Context, transaction model.Transaction) error {
	ret := _m.Called(ctx, transaction)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Transaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
