// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import detailcalculationmodel "github.com/tumpal2796/shopee/calculator/detailcalculation/model"

import mock "github.com/stretchr/testify/mock"
import model "github.com/tumpal2796/shopee/transaction/model"

// CalculatorInf is an autogenerated mock type for the CalculatorInf type
type CalculatorInf struct {
	mock.Mock
}

// GetDetailCalculation provides a mock function with given fields: transaction
func (_m *CalculatorInf) GetDetailCalculation(transaction model.Transaction) detailcalculationmodel.DetailCalc {
	ret := _m.Called(transaction)

	var r0 detailcalculationmodel.DetailCalc
	if rf, ok := ret.Get(0).(func(model.Transaction) detailcalculationmodel.DetailCalc); ok {
		r0 = rf(transaction)
	} else {
		r0 = ret.Get(0).(detailcalculationmodel.DetailCalc)
	}

	return r0
}
